from nicegui import ui
import pandas as pd
import io

ui.label("Movie HTML Creator").classes("text-2xl mb-4")

movies = []

async def load_csv(e):
    global movies

    # SmallFileUpload object
    uploaded = e.file

    # MUST await read()
    content = await uploaded.read()
    content = content.decode('utf-8')

    df = pd.read_csv(io.StringIO(content))
    movies = df.to_dict(orient='records')

    ui.notify(f"Loaded {len(movies)} movies")
    show_movie_grid()


def show_movie_grid():
    grid.clear()

    with grid:
        ui.html("<h2>Movie Gallery</h2>")

        with ui.row().classes("flex-wrap gap-4"):
            for movie in movies:
                poster = movie.get("Image URL", "")
                title = movie.get("Title", "Untitled")

                with ui.card().classes("w-48"):
                    ui.image(poster).classes("w-full h-64 object-cover rounded")
                    ui.label(title).classes("text-center text-sm mt-2")

                    ui.button("Details", on_click=lambda m=movie: show_popup(m)) \
                        .classes("mt-2 w-full")

def show_popup(movie):
    with ui.dialog() as dialog:
        with ui.card().classes("p-4 w-96"):
            ui.label(movie.get("Title", "")).classes("text-xl mb-2")

            html = "<ul style='line-height:1.6;'>"
            html += f"<li><b>Year:</b> {movie.get('Year')}</li>"
            html += f"<li><b>Rating:</b> {movie.get('Rating')}</li>"
            html += f"<li><b>Director:</b> {movie.get('Director')}</li>"
            html += f"<li><b>Writer:</b> {movie.get('Writer')}</li>"
            html += f"<li><b>Description:</b> {movie.get('Description')}</li>"
            html += f"<li><b>Cast:</b> {movie.get('Cast')}</li>"
            html += f"<li><b>Link:</b> <a href='{movie.get('Link')}' target='_blank'>Open TMDB</a></li>"
            html += "</ul>"

            ui.html(html)
            ui.button("Close", on_click=dialog.close).classes("mt-2")

    dialog.open()

def generate_html():
    html_output.clear()

    html = """
    <html>
    <head>
        <title>Movie Report</title>
        <style>
            body { font-family: Arial; padding: 20px; background: #f5f5f5; }
            header, footer { text-align: center; padding: 10px; background: #222; color: white; }
            .movie { margin-bottom: 40px; padding: 20px; background: white; border-radius: 10px; }
            img { width: 150px; height: 225px; object-fit: cover; border-radius: 8px; }
            ul { line-height: 1.6; }
        </style>
    </head>
    <body>
        <header><h1>Movie Report</h1></header>
    """

    for movie in movies:
        html += "<div class='movie'>"
        html += f"<h2>{movie.get('Title')}</h2>"
        html += f"<img src='{movie.get('Image URL')}' />"
        html += "<ul>"
        for key, value in movie.items():
            html += f"<li><b>{key}:</b> {value}</li>"
        html += "</ul></div>"

    html += "<footer><p>Generated by NiceGUI Movie Creator</p></footer>"
    html += "</body></html>"

    ui.html(html, container=html_output)

ui.upload(on_upload=load_csv).classes("mb-4")

grid = ui.column()
html_output = ui.column()

ui.button("Generate HTML Page", on_click=generate_html).classes("mt-4")

ui.run()
